/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package appKursusAmd;

import javax.swing.JPanel;
import java.awt.CardLayout;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import java.util.Calendar;
import java.util.GregorianCalendar;

/**
 *
 * @author SKYDEV2
 */
public class formUtama extends javax.swing.JFrame {
    private JPanel childpanel;
    

    /**
     * Creates new form formUtama
     */
    public formUtama() {
        initComponents();
        this.setLocationRelativeTo(null);
        splash();
 
    }
    
    private void splash(){
        childpanel=new splashScreen();
      pnMain.removeAll();
      pnMain.add(childpanel);
      pnMain.validate();
    }
    
     

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lbl_jam = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        btn_baru = new javax.swing.JButton();
        btn_tunggu = new javax.swing.JButton();
        btn_aktif = new javax.swing.JButton();
        btn_exit = new javax.swing.JButton();
        btn_status = new javax.swing.JButton();
        btn_sertifikat = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        btn_home = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        pnMain = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 102));
        jPanel1.setPreferredSize(new java.awt.Dimension(1200, 100));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Aplikasi Kursus AMD Drafting School");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 840, 50));

        lbl_jam.setBackground(new java.awt.Color(153, 153, 0));
        lbl_jam.setFont(new java.awt.Font("Clarendon Lt BT", 1, 18)); // NOI18N
        lbl_jam.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(lbl_jam, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 4, 130, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 50));

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setPreferredSize(new java.awt.Dimension(1200, 600));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(153, 153, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_baru.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_baru.setIcon(new javax.swing.ImageIcon(getClass().getResource("/appKursusAmd/siswa baru.png"))); // NOI18N
        btn_baru.setText("Data Siswa");
        btn_baru.setToolTipText("Siswa baru");
        btn_baru.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.orange, java.awt.Color.orange));
        btn_baru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_baruActionPerformed(evt);
            }
        });
        jPanel3.add(btn_baru, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 110, 30));

        btn_tunggu.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_tunggu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/appKursusAmd/tunggu.png"))); // NOI18N
        btn_tunggu.setText("Daftar tunggu");
        btn_tunggu.setToolTipText("Melihat siswa yang sudah mendaftar tapi belum lunas pembayaranya");
        btn_tunggu.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.orange, java.awt.Color.orange));
        btn_tunggu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tungguActionPerformed(evt);
            }
        });
        jPanel3.add(btn_tunggu, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 0, 130, 30));

        btn_aktif.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_aktif.setIcon(new javax.swing.ImageIcon(getClass().getResource("/appKursusAmd/aktif.png"))); // NOI18N
        btn_aktif.setText("Daftar Aktif");
        btn_aktif.setToolTipText("Melihat daftar siswa aktif");
        btn_aktif.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.orange, java.awt.Color.orange));
        btn_aktif.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_aktifActionPerformed(evt);
            }
        });
        jPanel3.add(btn_aktif, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 0, 110, 30));

        btn_exit.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/appKursusAmd/keluar.png"))); // NOI18N
        btn_exit.setText("Keluar");
        btn_exit.setToolTipText("Keluar aplikasi");
        btn_exit.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.orange, java.awt.Color.orange));
        btn_exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_exitActionPerformed(evt);
            }
        });
        jPanel3.add(btn_exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 0, 100, 30));

        btn_status.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_status.setIcon(new javax.swing.ImageIcon(getClass().getResource("/appKursusAmd/status.png"))); // NOI18N
        btn_status.setText("Status Siswa");
        btn_status.setToolTipText("Melihat Status siswa");
        btn_status.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.orange, java.awt.Color.orange));
        btn_status.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_statusActionPerformed(evt);
            }
        });
        jPanel3.add(btn_status, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 0, 110, 30));

        btn_sertifikat.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_sertifikat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/appKursusAmd/sertifikat.png"))); // NOI18N
        btn_sertifikat.setText("Sertifikat");
        btn_sertifikat.setToolTipText("Melihat daftar sertifikat");
        btn_sertifikat.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.orange, java.awt.Color.orange));
        btn_sertifikat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sertifikatActionPerformed(evt);
            }
        });
        jPanel3.add(btn_sertifikat, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 0, 100, 30));
        jPanel3.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, -30, 570, 10));

        btn_home.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/appKursusAmd/home.png"))); // NOI18N
        btn_home.setText("Home");
        btn_home.setToolTipText("Home aplikasi");
        btn_home.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.orange, java.awt.Color.orange));
        btn_home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_homeActionPerformed(evt);
            }
        });
        jPanel3.add(btn_home, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 0, 80, 30));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 30));

        jPanel4.setBackground(new java.awt.Color(0, 0, 102));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("By agik setiawan - 0878 3305 1035");
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 4, -1, 40));

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 600, 1200, 50));

        pnMain.setLayout(new java.awt.CardLayout());
        jPanel2.add(pnMain, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 1200, 570));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 1200, 650));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_exitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btn_exitActionPerformed

    /*button tambah baru*/
    private void btn_baruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_baruActionPerformed
      childpanel=new formSiswaBaru();
      pnMain.removeAll();
      pnMain.add(childpanel);
      pnMain.validate();
    }//GEN-LAST:event_btn_baruActionPerformed

    private void btn_tungguActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tungguActionPerformed
        // TODO add your handling code here:
        childpanel=new formSiswaTunggu();
      pnMain.removeAll();
      pnMain.add(childpanel);
      pnMain.validate();
    }//GEN-LAST:event_btn_tungguActionPerformed

    private void btn_aktifActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_aktifActionPerformed
        // TODO add your handling code here:
        childpanel=new formSiswaAktif();
      pnMain.removeAll();
      pnMain.add(childpanel);
      pnMain.validate();
    }//GEN-LAST:event_btn_aktifActionPerformed

    private void btn_statusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_statusActionPerformed
        // TODO add your handling code here:
        childpanel=new formStatusSiswa();
      pnMain.removeAll();
      pnMain.add(childpanel);
      pnMain.validate();
    }//GEN-LAST:event_btn_statusActionPerformed

    private void btn_homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_homeActionPerformed
        // TODO add your handling code here:
        splash();
    }//GEN-LAST:event_btn_homeActionPerformed

    private void btn_sertifikatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sertifikatActionPerformed
        // TODO add your handling code here:
        
        childpanel=new sertifikat();
      pnMain.removeAll();
      pnMain.add(childpanel);
      pnMain.validate();
    }//GEN-LAST:event_btn_sertifikatActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formUtama().setVisible(true);
                
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_aktif;
    private javax.swing.JButton btn_baru;
    private javax.swing.JButton btn_exit;
    private javax.swing.JButton btn_home;
    private javax.swing.JButton btn_sertifikat;
    private javax.swing.JButton btn_status;
    private javax.swing.JButton btn_tunggu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel lbl_jam;
    private javax.swing.JPanel pnMain;
    // End of variables declaration//GEN-END:variables
}
